accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('reset_password/', views.reset_password, name='reset-password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset-password-validate'),
    path('reset_password_detail/', views.reset_password_detail, name='reset-password-detail'),
    path('my_orders/', views.my_orders , name='my-orders'),
    path('edit_profile/', views.edit_profile , name='edit-profile'),
    path('change_password/', views.change_password , name='change-password'),
    path('order_detail/<int:order_id>/', views.order_detail , name='order-detail'),
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns =[
    path('', views.cart, name="cart"),
    path('add_cart/<int:product_id>/', views.add_cart, name='add-cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove-cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove-cart-item'),
    path('checkout', views.checkout, name='checkout'),

]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls', namespace='stores')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class MyAccountManager(BaseUserManager):
    def create_user(self,first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('User must have an email address')
        
        if not username:
            raise ValueError('User must have a username')
        
        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, first_name, last_name, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
            first_name=first_name,
            last_name=last_name,
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user

class Account(AbstractBaseUser):
    first_name   = models.CharField(max_length=50)
    last_name    = models.CharField(max_length=50)
    username     = models.CharField(max_length=50, unique=True)
    email        = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=50)

    # required
    date_joined    = models.DateTimeField(auto_now_add=True)
    last_login      = models.DateTimeField(auto_now_add=True)
    is_admin        = models.BooleanField(default=False)
    is_staff        = models.BooleanField(default=False)
    is_active       = models.BooleanField(default=False)
    is_superadmin   = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = MyAccountManager()

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True


class UserProfile(models.Model):
    user = models.OneToOneField(Account,on_delete=models.CASCADE)
    address_line_1  = models.CharField(blank=True,max_length=100)
    address_line_2  = models.CharField(blank=True,max_length=100)
    profile_picture = models.ImageField(blank=True, upload_to='userprofile')
    city            = models.CharField(blank=True, max_length=20)
    state           = models.CharField(blank=True, max_length=20)
    country         = models.CharField(blank=True, max_length=20)

    def __str__(self) -> str:
        return self.user.first_name
    
    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'

accounts/forms.py
from django import forms
from .models import Account, UserProfile

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password'
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password'
    }))
    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'phone_number', 'email', 'password']

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter Last Name'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Email'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Enter Phone Number'
        for field_name, field in self.fields.items():
            if field.widget.attrs.get('class'):
                field.widget.attrs['class'] += ' form-control'
            else:
                field.widget.attrs['class']='form-control'

    def clean(self):
        cleaned_data = super(RegistrationForm,self).clean()
        password            = cleaned_data.get('password')
        confirm_password    = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                "Password does not match!"
            )

class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'phone_number')
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = ' form-control'


class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False,error_messages={'invalid':("Images files only")}, widget=forms.FileInput)

    class Meta:
        model = UserProfile
        fields = ('address_line_1', 'address_line_2', 'city', 'state', 'country', 'profile_picture' )
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = ' form-control'

accounts/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from .forms import RegistrationForm, UserForm, UserProfileForm
from .models import Account, UserProfile
from orders.models import Order,OrderProduct
from carts.models import Cart, CartItem
from carts.views import _cart_id
from django.contrib.auth.hashers import make_password
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
import requests

# verification send email
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name      = form.cleaned_data['first_name']
            last_name       = form.cleaned_data['last_name']
            phone_number    = form.cleaned_data['phone_number']
            email           = form.cleaned_data['email']
            password        = form.cleaned_data['password']
            username        = email.split("@")[0]

            user = Account.objects.create(first_name=first_name,
                                          last_name=last_name,                                          
                                          email=email,
                                          username=username,
                                          password=make_password(password))
            user.phone_number = phone_number
            user.save()

            # create user profile
            profile = UserProfile()
            profile.user_id = user.id #TODO check if user id exist, delete the user id profile before save
            profile.profile_picture = 'default/default-user.png'
            profile.save()




            # user activation
            current_site = get_current_site(request)
            mail_subject = "Please activate your account"
            message = render_to_string('accounts/account_verification_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject,message,to=[to_email])
            send_email.send()
            # messages.success(request, 'We have received your registration. Please verify you email address by clicking on the link that we have sent you.')
            return redirect('/accounts/login/?command=verification&email='+ email)
    else: #render the empty   
        form = RegistrationForm()
    context = {
            'form':form,
        }

    return render(request, 'accounts/register.html', context)

def login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(email=email,password=password)
        if user is not None:

            # checking if cart items exists before login
            try:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                is_cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                if is_cart_item_exists:
                    cart_item = CartItem.objects.filter(cart=cart)

                    product_variation =[]
                    for item in cart_item:
                        variation = item.variations.all()
                        product_variation.append(list(variation))

                    cart_item = CartItem.objects.filter(user=user)
                    ex_var_list = []
                    id = []
                    for item in cart_item:
                        existing_variation  = item.variations.all()
                        ex_var_list.append(list(existing_variation)) 
                        id.append(item.id)

                    for pr in product_variation:
                        if pr in ex_var_list:
                            index = ex_var_list.index(pr)
                            item_id = id[index]
                            item = CartItem.objects.get(id=item_id)
                            item.quantity += 1
                            item.user = user
                            item.save()

            except:
                pass

            auth.login(request, user)
            messages.success(request, 'You are now logged in.')
            url = request.META.get('HTTP_REFERER')
            try:
                print(url)
                query = requests.utils.urlparse(url).query
                print('query -->', query)
                params = dict(x.split('=') for  x in query.split('&'))
                print('query -->', query)
                if 'next' in params:
                    nextPage = params['next']
                    return redirect(nextPage) 
            except:
                return redirect('accounts:dashboard')
            
        else:
            messages.error(request,'Invalid login credentials')
            return redirect('accounts:login')
    return render(request, 'accounts/login.html')

@login_required(login_url = 'accounts:login')
def logout(request):
    auth.logout(request)
    messages.success(request, 'You are logged out.')
    return redirect('accounts:login')


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)

    except(TypeError,ValueError,OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user,token):
        user.is_active = True
        user.save()
        messages.success(request, "Congratulations! Your account is activated.")
        return redirect('accounts:login')
    else:
        messages.error(request, "Invalid registration link")
        return redirect('accounts:register')
    
@login_required(login_url='accounts:login')
def dashboard(request):
    orders       = Order.objects.order_by('-created_at').filter(user_id=request.user.id, is_ordered=True)
    orders_count = orders.count()
    user_profile = UserProfile.objects.get(user_id = request.user.id)

    context = {
        'orders_count': orders_count,
        'user_profile'  : user_profile,
    }

    return render(request, 'accounts/dashboard.html', context)

def reset_password(request):
    if request.method == 'POST':
        email = request.POST['email']
        user_exist = Account.objects.filter(email__exact=email).exists()
        if user_exist:
            user = Account.objects.get(email=email)
            # user reset password
            current_site = get_current_site(request)
            mail_subject = "Reset your passoword"
            message = render_to_string('accounts/reset_password_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject,message,to=[to_email])
            send_email.send()
            messages.success(request, 'Password reset email has been sent to your email: ' + email)
            return redirect('accounts:login')
        else:
            messages.error(request, 'No user associated with the email provided!')
            return redirect('accounts:reset-password')

    return render(request, 'accounts/reset_password.html')
     
    
def reset_password_validate(request,uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)

    except(TypeError,ValueError,OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user,token):
        request.session['uid'] = uid
        messages.success(request, "Please reset your password.")
        return redirect('accounts:reset-password-detail')
    else:
        messages.error(request, "Invalid password reset link or link has expired!")
        return redirect('accounts:password-reset')
    

def reset_password_detail(request):
    if request.method == 'POST':
        password            = request.POST['password']
        confirm_password    = request.POST['confirm_password']
        if password == confirm_password:
            user = Account.objects.get(pk=request.session.get('uid'))
            user.set_password(password)
            user.save()
            messages.success(request,'Password reset was succesful')
            return redirect('accounts:login')

        else:
            messages.error(request, 'Password did not match!')
            return redirect('accounts:reset-password-detail')
    else:
        return render(request, 'accounts/reset_password_detail.html')
    
def my_orders(request):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by('-created_at')

    context = {
        'orders': orders,
    }
    return render(request, 'accounts/my_orders.html', context)

def edit_profile(request):
    
    userprofile = get_object_or_404(UserProfile, user=request.user)
    
    if request.method == 'POST':
        user_form       = UserForm(request.POST, instance=request.user)
        profile_form    = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile has been updated.')
            return redirect('accounts:edit-profile')
    else:

templates/accounts/account_verification_email.html
{% autoescape off %}
Hi {{user.first_name}},

Please click on the below link to confirm your registration:

http://{{domain}}{% url 'accounts:activate' uidb64=uid token=token %}

If this was sent not intended to you, please ignore or delete this email.

Thanks
GreatKart Admin
  
{% endautoescape %}

templates/accounts/change_password.html
{% extends "base.html" %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
    {% include 'includes/alerts.html' %}
    <div class="container">
        <div class="row">
            {% include 'includes/dashboard_sidebar.html' %}
            <main class="col-md-9">
                <article class="card">
                    <header class="card-header">
                        <strong class="d-inline-block mr-3">Change Your Password</strong>

                    </header>
                    <div class="card-body" style="text-align:left;">
                        <div class="row">
                            <!-- row1 -->
                            <div class="col-md-12">
                                <form action="{% url 'accounts:change-password' %}" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
 
                                    <!-- row 3 -->
                                    <div class="form-group">
                                        <label>Current Password</label>
                                       <input type="password" name="current_password" placeholder="Current Password" required class="form-control">
                                    </div>
                                    <!-- row 4 -->
                                    <div class="form-group">
                                        <label>Create New Password</label>
                                        <input type="password" name="new_password" placeholder="Create New Password" required class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label>Confirm New Password</label>
                                        <input type="password" name="confirm_password" placeholder="Confirm New Password" required class="form-control">
                                    </div>
                                    <input type="submit" value="Submit" class="btn btn-primary">
                                </form>


                            </div>


                        </div> <!-- row.// -->
                    </div> <!-- card-body .// -->

                </article> <!-- order-group.// -->
            </main>
        </div> <!-- row.// -->
    </div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/accounts/dashboard.html
{% extends "base.html" %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
    {% include 'includes/alerts.html' %}
    <div class="container">
        <div class="row">
            {% include 'includes/dashboard_sidebar.html' %}
            <main class="col-md-9">
                <article class="card">
                    <header class="card-header">
                        <strong class="d-inline-block mr-3">Logged in as:</strong>
                        <span>{{user.full_name}}</span>
                    </header>
                    <div class="card-body" style="text-align: center;">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title">Order Total</h5>
                                        <h4>{{orders_count}}</h4>
                                        <a href="{% url 'accounts:my-orders' %}">View Orders</a>
                                    </div>

                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="card">
                                    <div class="card-body" >
                                        <h5 class="card-title" style="text-align: center;">Profile</h5>
                                        <img src="{{user_profile.profile_picture.url}}" alt="Avatar"
                                            class="avatar">
                                            <p class="mb-0">{{user.email}}</p>
                                            <p>{{user.phone_number}}</p>
                                    </div>
                                </div>
                            </div>


                        </div> <!-- row.// -->
                    </div> <!-- card-body .// -->

                </article> <!-- order-group.// -->
            </main>
        </div> <!-- row.// -->
    </div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/accounts/edit_profile.html
{% extends "base.html" %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
    {% include 'includes/alerts.html' %}
    <div class="container">
        <div class="row">
            {% include 'includes/dashboard_sidebar.html' %}
            <main class="col-md-9">
                <article class="card">
                    <header class="card-header">
                        <strong class="d-inline-block mr-3">Edit your profile</strong>

                    </header>
                    <div class="card-body" style="text-align:left;">
                        <div class="text-right">
                            <img src="{{userprofile.profile_picture.url}}" alt="Profile Picture" width="100" style="border-radius:50% ;">
                        </div>
                        <div class="row">
                            <!-- row1 -->
                            <div class="col-md-12">
                                <form action="{% url 'accounts:edit-profile' %}" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                            <label>First Name</label>
                                            {{user_form.first_name}}
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>Last Name</label>
                                            {{user_form.last_name}}
                                        </div>
                                    </div>
                                    <!-- row2 -->
                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                            <label>Phone Number</label>
                                            {{user_form.phone_number}}
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>Profile Picture</label>
                                            {{profile_form.profile_picture}}
                                        </div>
                                    </div>
                                    <!-- row 3 -->
                                    <div class="form-group">
                                        <label>Address Line 1</label>
                                        {{profile_form.address_line_1}}
                                    </div>
                                    <!-- row 4 -->
                                    <div class="form-group">
                                        <label>Address Line 2</label>
                                        {{profile_form.address_line_2}}
                                    </div>
                                    <!-- row 5 -->
                                    <div class="form-row">
                                        <div class="form-group col-md-4">
                                            <label>City</label>
                                            {{profile_form.city}}
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>State</label>
                                            {{profile_form.state}}
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>Country</label>
                                            {{profile_form.country}}
                                        </div>
                                    </div>
                                    <input type="submit" value="Save" class="btn btn-primary">
                                </form>


                            </div>


                        </div> <!-- row.// -->
                    </div> <!-- card-body .// -->

                </article> <!-- order-group.// -->
            </main>
        </div> <!-- row.// -->
    </div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/accounts/my_orders.html
{% extends "base.html" %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
    {% include 'includes/alerts.html' %}
    <div class="container">
        <div class="row">
            {% include 'includes/dashboard_sidebar.html' %}
            <main class="col-md-9">
                <article class="card">
                    <header class="card-header">
                        <strong class="d-inline-block mr-3">Your order history:</strong>

                    </header>
                    <div class="card-body" style="text-align: center;">
                        <div class="row">

                            <div class="col-md-12">
                                <table class="table table-hover">
                                    <thead>
                                      <tr>
                                        <th scope="col">Order #</th>
                                        <th scope="col">Billing Name</th>
                                        <th scope="col">Phone</th>
                                        <th scope="col">Order Total</th>
                                        <th scope="col">Date</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                        {% for order in orders  %}
                                        <tr>
                                            <th scope="row"> <a href="{% url 'accounts:order-detail' order.order_number %}">{{order.order_number}}</a></th>
                                            <td>{{order.full_name}}</td>
                                            <td>{{order.phone_number}}</td>
                                            <td>${{order.order_total}}</td>
                                            <td>{{order.created_at}}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                  </table>
                            </div>


                        </div> <!-- row.// -->
                    </div> <!-- card-body .// -->

                </article> <!-- order-group.// -->
            </main>
        </div> <!-- row.// -->
    </div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/accounts/reset_password.html
{% extends "base.html" %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->

        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
          <div class="card-body">
            <h4 class="card-title mb-4">Forget Password</h4>
          {% include 'includes/alerts.html' %}
          <form action="{% url 'accounts:reset-password' %}" method="POST" >
            {% csrf_token %}
              <div class="form-group">
                 <input type="email" class="form-control" placeholder="Email Address" name="email" >
              </div> <!-- form-group// -->
              <div class="form-group">
                  <a href="{% url 'accounts:login' %}" class="float-right">Already have a password?</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block"> Submit  </button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->

    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    
{% endblock content %}

templates/accounts/reset_password_email.html
{% autoescape off %}
Hi {{user.first_name}},

As requested, please click on the below link to reset your password:

http://{{domain}}{% url 'accounts:reset-password-validate' uidb64=uid token=token %}

If this was sent not intended to you, please ignore or delete this email.

Thanks
GreatKart Admin
  
{% endautoescape %}