accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('reset_password/', views.reset_password, name='reset-password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset-password-validate'),
    path('reset_password_detail/', views.reset_password_detail, name='reset-password-detail'),
    path('my_orders/', views.my_orders , name='my-orders'),
    path('edit_profile/', views.edit_profile , name='edit-profile'),
    path('change_password/', views.change_password , name='change-password'),
    path('order_detail/<int:order_id>/', views.order_detail , name='order-detail'),
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns =[
    path('', views.cart, name="cart"),
    path('add_cart/<int:product_id>/', views.add_cart, name='add-cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove-cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove-cart-item'),
    path('checkout', views.checkout, name='checkout'),

]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls', namespace='stores')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'stores'

urlpatterns =[
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='product-by-category'),
    path('category/<slug:category_slug>/<slug:product_slug>', views.product_detail, name='product-detail'),
    path('search/', views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit-review'),
]

templates/includes/alerts.html
{% if messages %}

{% for message in messages %}
<div id="message" class="container">
    <div{% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </div>
</div>
<script>
    setTimeout(function () {
        var message = document.getElementsByClassName("message")[0];
        messages.parentNode.removeChild(message);
    }, 5000);
</script>
{% endfor %}

{% endif %}

templates/includes/dashboard_sidebar.html
<aside class="col-md-3">
    <!--   SIDEBAR   -->
    <ul class="list-group">
        {% if request.path == '/accounts/dashboard/'  %}
            <a class="list-group-item active" href="{% url 'accounts:dashboard' %}"> Dashboard</a>
        {% else %}
            <a class="list-group-item" href="{% url 'accounts:dashboard' %}"> Dashboard</a>
        {% endif %}

        {% if request.path == '/accounts/my_orders'  %}
        <a class="list-group-item active" href="{% url 'accounts:my-orders' %}"> My Orders</a>
        {% else %}
        <a class="list-group-item" href="{% url 'accounts:my-orders' %}"> My Orders</a>
        {% endif %}

        {% if request.path == '/accounts/edit_profile'  %}
        <a class="list-group-item active" href="{% url 'accounts:edit-profile' %}"> Edit Profile </a>
        {% else %}
        <a class="list-group-item" href="{% url 'accounts:edit-profile' %}"> Edit Profile </a>
        {% endif %}

        {% if request.path == '/accounts/change_password' %}
        <a class="list-group-item active" href="{% url 'accounts:change-password' %}"> Change Password </a>
        {% else %}
        <a class="list-group-item" href="{% url 'accounts:change-password' %}"> Change Password </a>
        {% endif %}

    </ul>
    <br>
    <a class="btn btn-light btn-block" href="{% url 'accounts:logout' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a> 
    <!--   SIDEBAR .//END   -->
</aside>

templates/includes/footer.html
<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2019 Picxel Studio </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">info@picxelstudio.com</span>
				<span  class="px-2">+6012-2309536</span>
				<span  class="px-2">Jalan Sunsuria 3B/10</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script>
	$(document).ready(function(){
		$('.thumb a').click(function(e){
			e.preventDefault();
			$('.mainImage img').attr('src', $(this).attr("href"));
		})
	})
</script>



</body>
</html>

templates/includes/navbar.html
{% load static %}
<header class="section-header">
    <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTop4">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                 <a href="#" class="nav-link">   English </a>
                
            </li>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link"> USD </a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
            <li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
        </ul> <!-- list-inline //  -->
      </div> <!-- navbar-collapse .// -->
    </div> <!-- container //  -->
    </nav>
    
    <section class="header-main border-bottom">
        <div class="container">
    <div class="row align-items-center">
        <div class="col-lg-2 col-md-3 col-6">
            <a href="{% url 'home' %}" class="brand-wrap">
                <img class="logo" src="{% static './images/logo.png' %}">
            </a> <!-- brand-wrap.// -->
        </div>
        <div class="col-lg col-sm col-md col-6 flex-grow-0">
            <div class="category-wrap dropdown d-inline-block float-right">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> 
                    <i class="fa fa-bars"></i> All category 
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'stores:store' %}">All Products</a>
                    {% for category in links %}
                        <a class="dropdown-item" href="{{category.get_url}}">{{category.category_name}}</a>
                    {% endfor %}
                </div>
            </div>  <!-- category-wrap.// -->
        </div> <!-- col.// -->
        <a href="{% url 'stores:store' %}" class="btn btn-outline-primary">Store</a>
        <div class="col-lg  col-md-6 col-sm-12 col">
            <form action="{% url 'stores:search' %}" class="search" method="GET">
                <div class="input-group w-100">
                    <input type="text" class="form-control" style="width:60%;" placeholder="Search" name="keyword">
                    
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="submit">
                        <i class="fa fa-search"></i>
                      </button>
                    </div>
                </div>
            </form> <!-- search-wrap .end// -->
        </div> <!-- col.// -->
        <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div class="d-flex justify-content-end mb-3 mb-lg-0">
                        {% if user.id is not NONE %}
                        <div class="widget-header">
                            <small class="title text-muted">Welcome {{user.first_name}} {{user.last_name}}!</small>
                            <div> 
                                <a href="{% url 'accounts:dashboard' %}">Dashboard</a> <span class="dark-transp"> | </span>
                                <a href="{% url 'accounts:logout' %}"> Logout</a>
                            </div>
                        </div>
                        {%else%}
                        <div class="widget-header">
                            <small class="title text-muted">Welcome guest!</small>
                            <div> 
                                <a href="{% url 'accounts:login' %}">Sign in</a> <span class="dark-transp"> | </span>
                                <a href="{% url 'accounts:register' %}"> Register</a>
                            </div>
                        </div>
                        {% endif %}
                        <a href="{% url 'carts:cart' %}" class="widget-header pl-3 ml-3">
                            <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                            <span class="badge badge-pill badge-danger notify">{{cart_counter}}</span>
                        </a>
                    </div> <!-- widgets-wrap.// -->
                </div> <!-- col.// -->
    </div> <!-- row.// -->
        </div> <!-- container.// -->
    </section> <!-- header-main .// -->
    
    
    
    
    </header> <!-- section-header.// -->
    