carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns =[
    path('', views.cart, name="cart"),
    path('add_cart/<int:product_id>/', views.add_cart, name='add-cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove-cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove-cart-item'),
    path('checkout', views.checkout, name='checkout'),

]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls', namespace='stores')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path, include
from .import views

app_name = 'orders'

urlpatterns = [
    path('place_order/', views.place_order , name='place-order'),
    path('payments/', views.payments, name='payments'),
    path('order_completed/', views.order_completed, name='order-completed'),
     
]

store/urls.py
from django.urls import path
from . import views

app_name = 'stores'

urlpatterns =[
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='product-by-category'),
    path('category/<slug:category_slug>/<slug:product_slug>', views.product_detail, name='product-detail'),
    path('search/', views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit-review'),
]

orders/models.py
from django.db import models
from accounts.models import Account
from store.models import Product, Variation
from django.db.models import Avg, Count


class Payment(models.Model):
    user            = models.ForeignKey(Account, on_delete=models.CASCADE)
    payment_id      = models.CharField(max_length=100)
    payment_method  = models.CharField(max_length=100)
    amount_paid     = models.CharField(max_length=100)
    status          = models.CharField(max_length=100)
    created_at      = models.DateTimeField(auto_now_add=True)
    modified_at     = models.DateTimeField(auto_now=True)



    def __str__(self):
        return self.payment_id
    
class Order(models.Model):
    status = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
        )

    user            = models.ForeignKey(Account,on_delete=models.SET_NULL, null=True)
    payment         = models.ForeignKey(Payment,on_delete=models.SET_NULL, null=True, blank=True)
    order_number    = models.CharField(max_length=20)
    first_name      = models.CharField(max_length=50)
    last_name       = models.CharField(max_length=50)
    phone_number    = models.CharField(max_length=15)
    email           = models.EmailField(max_length=50)
    address_line_1  = models.CharField(max_length=50)
    address_line_2  = models.CharField(max_length=50, blank=True)
    country         = models.CharField(max_length=50)
    state           = models.CharField(max_length=50)
    city            = models.CharField(max_length=50)
    order_note      = models.CharField(max_length=100, blank=True)
    order_total     = models.FloatField()
    tax             = models.FloatField()
    status          = models.CharField(max_length=10, choices=status, default='New')
    ip              = models.CharField(max_length=20, blank=True)
    is_ordered      = models.BooleanField(default=False)
    created_at      = models.DateTimeField(auto_now_add=True)
    modified_at     = models.DateTimeField(auto_now=True)

    def full_name(self):
        return self.first_name + ' ' + self.last_name
    
    def full_address(self):
        return self.address_line_1 + ' ' + self.address_line_2

    def __str__(self):
        return self.first_name
    

class OrderProduct(models.Model):
    order          = models.ForeignKey(Order,on_delete=models.CASCADE)            
    payment        = models.ForeignKey(Payment,on_delete=models.SET_NULL, blank=True, null=True)             
    user           = models.ForeignKey(Account,on_delete=models.CASCADE) 
    product        = models.ForeignKey(Product,on_delete=models.CASCADE) 
    variations     = models.ManyToManyField(Variation, blank=True)   
    quantity       = models.IntegerField()
    product_price  = models.FloatField()
    ordered        = models.BooleanField(default=False)
    created_at     = models.DateTimeField(auto_now_add=True)
    modified_at    = models.DateTimeField(auto_now=True) 

    def __str__(self) -> str:
        return self.product.product_name
    
    def save(self, *args, **kwargs):
        self.product_price = round(self.product_price, 2)
        super(OrderProduct, self).save(*args, **kwargs)

class ReviewRating(models.Model):
    product     = models.ForeignKey(Product, on_delete=models.CASCADE)
    user        = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject     = models.CharField(max_length=100, blank=True)
    review      = models.TextField(max_length=500,blank=True)
    rating      = models.FloatField()
    ip          = models.CharField(max_length=20,blank=True)
    status      = models.BooleanField(default=True)
    created_at  = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.product_name
    
    def average_review(self):
        reviews = ReviewRating.objects.filter(product=self,status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg
    
    def count_review(self):
        reviews = ReviewRating.objects.filter(product=self,status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count


    

orders/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 
                  'last_name', 
                  'phone_number', 
                  'email',
                  'address_line_1', 
                  'address_line_2', 
                  'country', 
                  'state', 
                  'city', 
                  'order_note']

orders/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from carts.models import CartItem
from .forms import OrderForm
from orders.models import Order, Payment, OrderProduct
from store.models import Product
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
import datetime
import json


def payments(request):
    body = json.loads(request.body)
    order = Order.objects.get(user=request.user, is_ordered=False, order_number=body['orderID'])
    # store transaction details inside payments

    payment = Payment(
        user            = request.user,
        payment_id      = body['transID'],
        payment_method  = body['payment_method'],
        amount_paid     = order.order_total,
        status          = body['status']
    )
    payment.save()

    order.payment       = payment
    order.is_ordered    = True
    order.save()

    # move cart item to order product table 
    cart_items = CartItem.objects.filter(user=request.user)

    for item in cart_items:
        order_product               = OrderProduct()
        order_product.order_id      = order.id 
        order_product.payment       = payment
        order_product.user_id       = request.user.id
        order_product.product_id    = item.product.id
        order_product.quantity      = item.quantity
        order_product.product_price = item.product.price
        order_product.ordered       = True
        order_product.save()

        cart_item           = CartItem.objects.get(id=item.id)
        product_variation   = cart_item.variations.all()
        order_product       = OrderProduct.objects.get(id=order_product.id)
        order_product.variations.set(product_variation)
        order_product.save()



        # reduct the quantity of sold product
        product = Product.objects.get(id=item.product_id)
        product.stock -= item.quantity
        product.save()

    # clear the cart item
    CartItem.objects.filter(user=request.user).delete()

    # send email to the customer
    mail_subject = "Thank you for your purchase!"
    message = render_to_string('orders/order_received_email.html', {
        'user': request.user,
        'order': order,
    })
    to_email = request.user.email
    send_email = EmailMessage(mail_subject,message,to=[to_email])
    send_email.send()

    # send back the transation id to the paypal
    data = {
        'order_number': order.order_number,
        'transID': payment.payment_id,
    }
    return JsonResponse(data)

def place_order(request, total=0, quantity=0):
    current_user = request.user
    cart_items    =  CartItem.objects.filter(user=current_user)

    if cart_items.count() <= 0:
        return redirect('stores:store')
    
    grand_total  = 0
    tax          = 0
    for cart_item in cart_items:
        total += (cart_item.product.price * cart_item.quantity)
        quantity += cart_item.quantity
    tax = round(total * 0.02,2) # times tax percentage parameter
    grand_total = round((tax + total),2)

    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            # store information in the order table
            data = Order()
            data.user           = current_user
            data.first_name     = form.cleaned_data['first_name']
            data.last_name      = form.cleaned_data['last_name']
            data.phone_number   = form.cleaned_data['phone_number']
            data.email          = form.cleaned_data['email']
            data.address_line_1 = form.cleaned_data['address_line_1']
            data.address_line_2 = form.cleaned_data['address_line_2']
            data.country        = form.cleaned_data['country']
            data.state          = form.cleaned_data['state']
            data.city           = form.cleaned_data['city']
            data.order_note     = form.cleaned_data['order_note']
            data.order_total    = grand_total
            data.tax            = tax
            data.ip             = request.META.get('REMOTE_ADDR')
            data.save()
            # generate order number
            yr = int(datetime.date.today().strftime('%Y'))
            dt = int(datetime.date.today().strftime('%d'))
            mt = int(datetime.date.today().strftime('%m'))
            d  = datetime.date(yr,mt,dt)
            current_date = d.strftime("%Y%m%d")
            order_number = current_date + str(data.id)
            data.order_number   = order_number
            data.save()

            order = Order.objects.get(user=current_user,is_ordered=False, order_number=order_number) 
            context = {
                'order'      :order,
                'cart_items' : cart_items,
                'tax'        : tax,
                'total'      : total,
                'grand_total': grand_total,
            }

            return render(request, 'orders/payments.html', context)
    else:
        return redirect('carts:checkout')
        

def order_completed(request):
    order_number    = request.GET.get('order_number')
    transID         = request.GET.get('payment_id')

    try:
        order               = Order.objects.get(order_number=order_number)
        ordered_products    = OrderProduct.objects.filter(order_id=order.id)
        payment             = Payment.objects.get(payment_id=transID)

        subtotal = 0
        for item in ordered_products:
            subtotal += item.product_price * item.quantity


        context = {
            'order'             : order,
            'ordered_products'  : ordered_products,
            'order_number'      : order_number,
            'transID'           : payment.payment_id,
            'payment'           : payment,
            'subtotal'          : subtotal,
        }
        return render(request, 'orders/order_completed.html', context)
    except(Payment.DoesNotExist, Order.DoesNotExist):
        return render('home')


    

templates/orders/order_completed.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container" style="margin-top: 50px;">
    <center><i class="fas fa-check-circle" style="font-size: 72px;margin-bottom: 20px;color: #28A745;"></i></center>
    <h2 class="text-center">Payment Successful</h2>
	<br>
	<div class="text-center">
		<a href="{% url 'stores:store' %}" class="btn btn-success">Shop more</a>
	</div>
</div>

<div class="container" style="margin: 0 auto;width: 50%;padding: 50px;background: #f1f1f1;margin-top: 50px;margin-bottom: 50px;">
    <div class="row invoice row-printable">
        <div class="col-md-12">
            <!-- col-lg-12 start here -->
            <div class="panel panel-default plain" id="dash_0">
                <!-- Start .panel -->
                <div class="panel-body p30">
                    <div class="row">
                        <!-- Start .row -->
                        <div class="col-lg-6">
                            <!-- col-lg-6 start here -->
                            <div class="invoice-logo"><img src=" {% static '/images/logo.png'  %}" alt="Invoice logo" style="max-height: 40px;"></div>
                        </div>
                        <!-- col-lg-6 end here -->
                        <div class="col-lg-6">
                            <!-- col-lg-6 start here -->
                            <div class="invoice-from">
                                <ul class="list-unstyled text-right">
                                    <li><strong>Invoiced To</strong></li>
                                    <li>{{ order.full_name}}</li>
                                    <li>{{ order.full_address}}</li>
                                    <li>{{ order.city }}, {{ order.state }}</li>
                                    <li>{{ order.country}}</li>
                                </ul>
                            </div>
                        </div>
                        <!-- col-lg-6 end here -->
                        <div class="col-lg-12">
                            <!-- col-lg-12 start here -->
                            <div class="invoice-details mt25">
                                <div class="well">
                                    <ul class="list-unstyled mb0">
                                        <li><strong>Order</strong> #{{ order_number }}</li>
                                        <li><strong>Transaction</strong> #{{transID }}</li>
                                        <li><strong>Order Date:</strong> {{ order.created_at }}</li>
                                        <li><strong>Status:</strong> {{ payment.status }}</li>
                                    </ul>
                                </div>
                            </div>
                           
                            <div class="invoice-items">
                                <div class="table-responsive" style="overflow: hidden; outline: none;" tabindex="0">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th class="per70 text-center">Products</th>
                                                <th class="per5 text-center">Qty</th>
                                                <th class="per25 text-center">Total</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for item in ordered_products  %}
                                            <tr>
                                                <td>{{item.product.product_name}}
                                                    <p class="text-muted small">
                                                        {% if item.variations.all %}
                                                            {% for item in item.variations.all %}
                                                               <small>{{item.variation_category | capfirst}}</small>:<small>{{item.variation_value | capfirst }}</small><br>
                                                            {% endfor %}  
                                                        {% endif %}
                                                    </p>
                                                </td>
                                                <td class="text-center">{{item.quantity}}</td>
                                                <td class="text-center">${{item.product_price | floatformat:2}} USD</td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th colspan="2" class="text-right">Sub Total:</th>
                                                <th class="text-center">${{subtotal |floatformat:2 }} USD</th>
                                            </tr>
                                            <tr>
                                                <th colspan="2" class="text-right">Tax:</th>
                                                <th class="text-center">${{order.tax}} USD</th>
                                            </tr>
                                            
                                            <tr>
                                                <th colspan="2" class="text-right">Grand Total:</th>
                                                <th class="text-center">${{order.order_total}} USD</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                            <div class="invoice-footer mt25">
                                <p class="text-center">Thank you for shopping with us!</p>
                            </div>
                        </div>
                        <!-- col-lg-12 end here -->
                    </div>
                    <!-- End .row -->
                </div>
            </div>
            <!-- End .panel -->
        </div>
        <!-- col-lg-12 end here -->
    </div>
    </div>

{% endblock content %}

templates/orders/order_received_email.html
{% autoescape off %}
Hi {{user.first_name}},

We have received your order: {{ order.order_number}}

Thanks
GreatKart Sales Team
  
{% endautoescape %}

templates/orders/payments.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <h4 class="text-center mb-10">Review Your Order and Make Payment</h4>
    <div class="row">
        <aside class="col-lg-8">
            <div class="card">
                <h5 class="card-header">Billing Address</h5>
                <div class="card-body">
                    <p class="card-text mb-0">{{ order.full_name }}</p>
                    <p class="card-text mb-0">{{ order.full_address }}</p>
                    <p class="card-text mb-0">{{ order.city }}, {{ order.state }}</p>
                    <p class="card-text mb-0">{{ order.country }}</p>
                    <p class="card-text mb-0">{{ order.email }}</p>
                    <p class="card-text mb-0">{{ order.phone_number }}</p>
                    {% if order.order_note %}
                    <b>Order Note:</b>
                    <p class="card-text mb-0">{{ order.order_note }}</p>
                    {% endif %}
                </div>
            </div>

            <div class="card">
                <h5 class="card-header">Payment Method</h5>
                <div class="card-body">
                    <p class="card-text">PayPal</p>
                </div>
            </div>

            <div class="card">
                <h5 class="card-header">Review Products</h5>
                <div class="card-body">
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                        <tr class="small text-uppercase">
                          <th scope="col">Product</th>
                          <th scope="col" width="120">Quantity</th>
                          <th scope="col" width="120">Price</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for cart_item in cart_items  %}
                        <tr>
                            <td>
                                <figure class="itemside align-items-center">
                                    <div class="aside"><img src=" {{ cart_item.product.images.url }}" class="img-sm"></div>
                                    <figcaption class="info">
                                        <a href="{{cart_item.product.get_url}}" class="title text-dark">{{cart_item.product.product_name}}</a>
                                        <p class="text-muted small">
                                            {% if cart_item.variations.all %}
                                                {% for item in cart_item.variations.all %}
                                                   <small>{{item.variation_category | capfirst}}</small>:<small>{{item.variation_value | capfirst }}</small><br>
                                                {% endfor %}  
                                            {% endif %}
                                        </p>
                    
                                    </figcaption>
                                </figure>
                            </td>
                            <td> 
                                <!-- col.// -->
                                <label for="">{{cart_item.quantity}}</label>
                            </td>
                            <td> 
                                <div class="price-wrap"> 
                                    <var class="price">${{cart_item.sub_total}}</var> 
                                    <small class="text-muted"> ${{cart_item.product.price}} each </small> 
                                </div> <!-- price-wrap .// -->
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                        </table>
                </div>
            </div>
    
        </aside> <!-- col.// -->
        <aside class="col-lg-4">
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">${{total}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Tax:</dt>
                  <dd class="text-right"> ${{tax}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Grand Total:</dt>
                  <dd class="text-right text-dark b"><strong>${{grand_total}}</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="{% static './images/misc/payments.png' %}" height="26">
                </p>
                <a href="{% url 'carts:checkout' %}" class="btn btn-primary btn-block"> Make Payment </a>
                <a href="{% url 'stores:store' %}" class="btn btn-light btn-block mb-10">Continue Shopping</a>
                <hr>

                <!-- Set up a container element for the button -->
                <div id="paypal-button-container"></div>

                
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    </div> <!-- container .//  -->
    </section>

<script>

    function getCookie(name){
        let cookieValue = null;
        if(document.cookie && document.cookie !==''){
            const cookies = document.cookie.split(';');
            for (let i=0; i < cookies.length; i++){
                const cookie  = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1 ) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var amount          = "{{ grand_total }}"
    var url             =  "{% url 'orders:payments' %}"
    var csrftoken       = getCookie('csrftoken');
    var orderID         = "{{ order.order_number}}"
    var payment_method  = 'PayPal'
    var redirect_url    = "{% url 'orders:order-completed' %}"

    paypal.Buttons({

        style: {
        layout:  'vertical',
        color:   'blue',
        shape:   'rect',
        label:   'paypal'
        },

        //setup the transaction
        createOrder: function(data, actions){
            return actions.order.create({
                purchase_units:[{
                    amount: {
                        value: amount,
                    }
                }]
            });
        },
        
        // finalise the transactions

        onApprove: function(data, actions) {
            return actions.order.capture().then(function(details) {
                // show success message to buyer
                console.log(details); 
                sendData();
                function sendData(){
                    fetch(url,{
                        method : "POST",
                        headers: {
                            "Content-type":"application/json",
                            "X-CSRFToken": csrftoken,
                        },
                        body: JSON.stringify({
                            orderID: orderID,
                            transID: details.id,
                            payment_method: payment_method,
                            status: details.status,
                        }),
                    })
                    .then((response) => response.json())
                    .then((data) => {
                        console.log('Success:',  data);
                        console.log('Transaction Completed.');
                        window.location.href = redirect_url + '?order_number='+data.order_number+'&payment_id='+data.transID;

                    });
                }
            });
        }
    }).render('#paypal-button-container');
</script>

{% endblock content %}